### ISSUE TITLE
Recommend hosting an arsha.oqtane.org for live demo

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/Oqtane.Theme.Arsha#1]
I think this would help people with a head start - ATM the videos are great, but seeing it in action would be better.

**Comment by rollsr1** [comment]
Yes please :)

**Comment by sbwalker** [comment]
@iJungleboy @rollsr1 the https://www.oqtane.org site is using a theme which uses the exact same approach as the Arsha theme (ie. based on a BootstrapMade template using AOS, etc....)
