### ISSUE TITLE
theme nor working in latest framework

### ISSUE THREAD

**Issue by rosdisulaiman** [oqtane/Oqtane.Theme.Arsha#6]
Hi,

i have download latest oqtane framework and then this Oqtane.Theme.Arsha.
Follow the instruction but the result are not as expected.
![2](https://github.com/user-attachments/assets/78f63f07-5265-4318-b8ff-9306874e83f0)
![1](https://github.com/user-attachments/assets/06ea92bf-9245-4f42-9b29-adfb563881fc)

**Comment by sbwalker** [comment]
@rosdisulaiman I just added some additional documentation to the home page:

"Note that you need to ensure that the folder is organized as a sibling of the Oqtane framework in your local environment (ie. it is located within the same parent folder):  

```
/parent
  /oqtane.framework
  /Oqtane.Theme.Arsha
```

Organizing the folders in this way allows the system to automatically deploy the module DLLs to the Oqtane framework when your build the theme solution."

**Comment by rosdisulaiman** [comment]
thank you for the update. it working now.
